import type { Course, ContentItem } from "@/types/academic"

export const sampleCourses: Course[] = [
  {
    id: "course-1",
    title: "Introduction to Artificial Intelligence",
    code: "CS 4320",
    description: "Comprehensive introduction to AI concepts, machine learning, and applications",
    status: "active",
    term: "Fall 2024",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-20"),
    enrolledStudents: 45,
    classes: [
      {
        id: "class-1",
        courseId: "course-1",
        number: 1,
        title: "What is AI?",
        description: "Introduction to artificial intelligence, its history, and applications",
        weekNumber: 1,
        order: 1,
        sessions: [
          {
            id: "session-1-1",
            classId: "class-1",
            number: 1,
            title: "AI History and Evolution",
            description: "From Turing to modern AI",
            estimatedTime: 45,
            content: [],
            learningGoals: [
              {
                id: "goal-1",
                sessionId: "session-1-1",
                statement: "Students will be able to describe the evolution of AI from 1950s to present",
                cognitiveLevel: "understand",
                knowledgeDimension: "conceptual",
                bloomCell: "2B",
                successCriteria: ["Identify key milestones", "Explain paradigm shifts"],
                masteryThreshold: 0.8,
              },
            ],
            status: "published",
            order: 1,
          },
          {
            id: "session-1-2",
            classId: "class-1",
            number: 2,
            title: "AI Applications Today",
            description: "Real-world applications across industries",
            estimatedTime: 60,
            content: [],
            learningGoals: [],
            status: "draft",
            order: 2,
          },
        ],
      },
      {
        id: "class-2",
        courseId: "course-1",
        number: 2,
        title: "Machine Learning Fundamentals",
        description: "Core concepts of supervised and unsupervised learning",
        weekNumber: 2,
        order: 2,
        sessions: [
          {
            id: "session-2-1",
            classId: "class-2",
            number: 1,
            title: "Supervised Learning",
            description: "Classification and regression techniques",
            estimatedTime: 90,
            content: [],
            learningGoals: [],
            status: "draft",
            order: 1,
          },
        ],
      },
    ],
  },
  {
    id: "course-2",
    title: "Culinary Arts: Professional Techniques",
    code: "CULN 2100",
    description: "Master professional cooking techniques and kitchen management",
    status: "active",
    term: "Spring 2024",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-03-15"),
    enrolledStudents: 28,
    classes: [],
  },
]

export const sampleContentLibrary: ContentItem[] = [
  {
    id: "content-1",
    type: "video",
    title: "Introduction to Neural Networks",
    url: "/videos/neural-networks-intro.mp4",
    fileSize: 125000000,
    uploadDate: new Date("2024-03-01"),
  },
  {
    id: "content-2",
    type: "pdf",
    title: "AI Ethics Guidelines",
    url: "/docs/ai-ethics.pdf",
    fileSize: 2500000,
    uploadDate: new Date("2024-03-05"),
  },
]
